travis:
  secure:
    BINSTAR_TOKEN: Zk/wRQPxqeEz5HeqDlHXBUAXSbBhwWBTWILHc8pP3fS7lBywf8kTO9i7fNg+1oPsRt+U8VSw67GgGdGIIQ7pF0O5ckfI0+lWrruRc6qWxadQtHnacNTjsJeHRA+fVF3eu+izIzxAwytUfRMxqudGEx2s+KAlsgxMzOJyFj8BYwp7fkWLHPQmWMwdfZRTE8nXARE5WbDhHcksh4kFFJsvvAJS0vNH/ax4Gk73trydP7FMlKjPCERPpLAFHPKU1hRX0NSkf7sY/HmGH/UMu8MxTPjM30s8zW6EpLfooasxqXCSZogwmWmWUZNmC1vWdjY3AsdLJzu94lnjnzy9UaYzShmOQrux0XR2bslReIsGiCexQ3rvFeBGffnfsFIcPWU8+8detYlOmxEKwihrszBnXtNhGruMUSt1jqmmI7Hb/hJhZj1xFfNS/IE5bV/dXwZH8Z/uLlNapjwTeLqUsUNm4814AM/LCbn93b48O/2Xi+p1LNV9JrEPFWzjEPWLruKtq0PbacR5J+imWkctasreythK3iHC+wQs52uk0tnmsM8xzI5t/4iOJNfmSXIh/XpVRj+rM5IiTKl5j1A17+IA7D/E+j9WcHv25NaFgcLNMWsWts+5g6VKczVA/LkEVRSAE+eYXF3KiijPJzF9T49s852rOdUX7nmdcsi7XBMtb0c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
